import { expect, test } from "@playwright/test";
import { PUZZLE } from "../fixtures";
import { cell, finishDraft, importText, openLibrary, openMenu, openSettings } from "./helpers";

test("new drafts get the next Puzzle number; names autosave while focused", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  const name = page.getByLabel("Puzzle name");
  await expect(name).toHaveValue("Puzzle 1");
  await name.fill("Nome sem sair do campo");
  await expect(name).toBeFocused();
  await expect(page.getByTestId("save-status")).toHaveText("Saved");
  await page.reload();
  await expect(page.getByLabel("Puzzle name")).toHaveValue("Nome sem sair do campo");
  await page.goto("/");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await expect(page.getByLabel("Puzzle name")).toHaveValue("Puzzle 1");
  await page.goto("/");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await expect(page.getByLabel("Puzzle name")).toHaveValue("Puzzle 2");
});

test("conflicting draft saves, cannot finish, and playable clues remain locked", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await cell(page, 0).click();
  await page.keyboard.press("1");
  await page.keyboard.press("ArrowRight");
  await page.keyboard.press("1");
  await expect(page.getByTestId("clue-summary")).toHaveText("2 cells in conflict");
  await expect(page.getByRole("button", { name: "Finish", exact: true })).toBeDisabled();
  await expect(page.getByTestId("save-status")).toHaveText("Saved");
  await page.reload();
  await expect(page.getByRole("button", { name: "Finish", exact: true })).toBeDisabled();
  await expect(cell(page, 1)).toHaveAttribute("aria-selected", "true");
  await page.keyboard.press("Backspace");
  await finishDraft(page);
  await page.getByRole("button", { name: "Play now", exact: true }).click();
  await cell(page, 0).click();
  await page.keyboard.press("9");
  await expect(cell(page, 0).locator("[data-value]")).toHaveText("1");
  await cell(page, 1).click();
  await page.keyboard.press("1");
  await expect(page.locator(".cell.conflict")).toHaveCount(0);
  await openSettings(page);
  await page.getByRole("switch", { name: "Warn on conflicting digits" }).check();
  await page.goBack();
  await expect(page.locator(".cell.conflict")).toHaveCount(2);
});

test("import preserves the current draft; copy and confirmed deletion preserve original progress", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await page.getByLabel("Puzzle name").fill("Meu rascunho");
  await page.getByLabel("Puzzle name").press("Enter");
  await page.getByRole("button", { name: "Import", exact: true }).click();
  await page.getByLabel("Puzzle text").fill("bad");
  await expect(page.getByRole("alert")).toContainText("needs 81");
  await expect(page.getByRole("button", { name: "Import as new draft", exact: true })).toBeDisabled();
  await page.getByLabel("Puzzle text").fill(PUZZLE);
  await expect(page.getByRole("dialog")).toContainText("30 clues");
  await page.getByRole("button", { name: "Import as new draft", exact: true }).click();
  await finishDraft(page);
  await page.getByRole("button", { name: "Play now", exact: true }).click();
  await cell(page, 2).click();
  await page.keyboard.press("4");
  const playUrl = page.url();
  await openLibrary(page);
  await page.getByRole("button", { name: /^More actions for/ }).click();
  await page.getByRole("menuitem", { name: "Edit a copy" }).click();
  await cell(page, 0).click();
  await page.keyboard.press("9");
  await page.goto(playUrl);
  await expect(cell(page, 0).locator("[data-value]")).toHaveText("5");
  await expect(cell(page, 2).locator("[data-value]")).toHaveText("4");
  await openLibrary(page);
  await page.getByRole("button", { name: /^More actions for/ }).click();
  await page.getByRole("menuitem", { name: "Delete" }).click();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("button", { name: /^Continue / })).toBeVisible();
  await page.getByRole("button", { name: /^More actions for/ }).click();
  await page.getByRole("menuitem", { name: "Delete" }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Delete", exact: true }).click();
  await expect(page.getByRole("button", { name: /^Continue / })).toHaveCount(0);
  await page.getByRole("button", { name: /^Drafts/ }).click();
  await expect(page.getByText("Meu rascunho", { exact: true })).toBeVisible();
});

test("library sends a puzzle straight to the solver, which can save it as a draft", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await importText(page, PUZZLE);
  await page.getByLabel("Puzzle name").fill("Morning");
  await finishDraft(page);
  await page.getByRole("button", { name: "Back to library", exact: true }).click();
  await page.getByRole("button", { name: "Solve Morning", exact: true }).click();
  await expect(page).toHaveURL(/#\/solve\/puzzle\//);
  await expect(page.getByLabel("Puzzle name")).toHaveValue("Morning");
  await expect(page.getByTestId("clue-summary")).toHaveText("30 clues");
  await expect(cell(page, 0).locator("[data-value]")).toHaveText("5");
  await page.reload();
  await expect(page.getByTestId("clue-summary")).toHaveText("30 clues");
  await openMenu(page, "Save as draft");
  await openLibrary(page);
  await page.getByRole("button", { name: /^Drafts/ }).click();
  await expect(page.getByText("Morning", { exact: true })).toBeVisible();
});
